### ISSUE TITLE
Build info error

### ISSUE THREAD

**Issue by SharkTankIndia** [hashlips-lab/nft-erc721-collection#214] opened 2022-04-05 11:33 UTC
while running yarn verify, I am getting this error"
[Error: ENOENT: no such file or directory, open 'C:\Users\dev\Desktop\nft-erc721-collection-main\smart-contract\artifacts\build-info\dbb0ed8fef0c7503b97499097ec4a1cc.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\dev\\Desktop\\nft-erc721-collection-main\\smart-contract\\artifacts\\build-info\\dbb0ed8fef0c7503b97499097ec4a1cc.json'
}
error Command failed with exit code 1.
![Screenshot (283)](https://user-images.githubusercontent.com/99258434/161745156-dc27dc04-d6b7-4022-8eb9-2af5618bdb85.png)

**Comment by liarco** [comment] 2022-04-05 11:42
Hi,
The bug report template requires some data that is missing here.

I'll give you some time to add the missing information, otherwise I will have to close the issue as invalid. Please keep in mind that if you don't provide us with the steps to reproduce this issue on our side, we won't be able to help you.

If you just have a general question and you don't think this is a bug, you might ask for support from the community in the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions). Thank you.

You can take a look at the issue template below:
https://github.com/hashlips-lab/nft-erc721-collection/blob/ecb19096f3dae6f29505d0d85a9844d7cf07d505/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L24-L51

**Comment by SharkTankIndia** [comment] 2022-04-06 04:47
### General information
| error while verifying the smart contract | [Error: ENOENT: no such file or directory, open 'C:\Users\dev\Desktop\nft-erc721-collection-main\smart-contract\artifacts\build-info\dbb0ed8fef0c7503b97499097ec4a1cc.json'] |
| --- | --- |
| Project version | 0.0.0 |
| Operating system and version | windows 10 home |
| NodeJS version | 14.16.1 |
| NPM version | 6.14.12 |
| Yarn version | 1.22.15 |
| Truffle version | 5.5.7|

### Describe the bug
While running the command "yarn verify 0xbca4FBDe64E4B5e67DA0CFD9bB45c619464820D3 --network truffle" i get this error 
[Error: ENOENT: no such file or directory, open 'C:\Users\dev\Desktop\nft-erc721-collection-main\smart-contract\artifacts\build-info\dbb0ed8fef0c7503b97499097ec4a1cc.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\dev\\Desktop\\nft-erc721-collection-main\\smart-contract\\artifacts\\build-info\\dbb0ed8fef0c7503b97499097ec4a1cc.json'
}
error Command failed with exit code 1.

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):
1. Go to 'cd smart-contract'
2. run 'yarn verify (your smart contract address) --network truffle'
3. Scroll down to 'an unexpected error occured'
4. See error

### Expected behavior
I expected to have the smart contract verified on rinkyby testnet.

### Screenshots
![Screenshot (284)_LI](https://user-images.githubusercontent.com/99258434/161897716-8e182fa7-a0ea-4101-a142-1de60f906ae2.jpg)

### Additional context
nothing more just that.

**Comment by liarco** [comment] 2022-04-06 08:34
Hi @SharkTankIndia,
I don't think this is a bug, you might have compiled multiple versions of the contract and now the compiler is confused by the multiple "cache" files.

First of all there is no version `0.0.0`, did you download the last commit from the `main` branch instead of a release tag?
The `main` branch contains the development version. It should be stable enough for testing, but it's not production-ready. I highly recommend sticking with stable releases instead.

To solve the error please try the following:
1. remove these folders from the `/smart-contract` path: `artifacts`, `cache`, `typechain`
2. run `yarn compile`
3. try verifying again

Let me know if this works.

**Comment by SharkTankIndia** [comment] 2022-04-06 10:31
hey there, 
I tried as you instructed me to but this time I am getting a different error.

HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (C:\Users\dev\Desktop\nft-erc721-collection-main\smart-contract\node_modules\undici\lib\client.js:1005:28)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}

![Screenshot (285)](https://user-images.githubusercontent.com/99258434/161955648-e52b2135-eec9-4f5b-b03b-29e17af8f92f.png)

**Comment by liarco** [comment] 2022-04-06 12:54
It seems like the CLI can't connect to the remote API for verifying the contract.

Please make sure that:
1. your wallet is connected to truffle dashboard
2. the correct network is selected on metamask

My only way to reproduce this error is by running the command while my wallet is not connected to the dashboard.

**Comment by SharkTankIndia** [comment] 2022-04-07 05:54
Which is the correct network sir?how do I use polygon?

**Comment by liarco** [comment] 2022-04-08 19:58
I think you are missing some basic concepts here, please follow [my tutorials](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) in order to understand the basics.

I have to close this issue since the error you are getting is not a bug, it seems like you have a bad configuration on your wallet or you are not confirming the transaction on metamask before the timeout kicks in. When opening an issue you will be guided about how to ask for support instead of opening a bug report.

Thank you.

**Closed by liarco** 2022-04-08 19:58 UTC
Labels: feedback requested

**Comment by victorfu** [comment] 2022-08-01 09:45
@SharkTankIndia I have the same problem when verifying contract on polygon testnet. I deleted artifacts and cache folders and rerun `yarn compile`. After that, my contract is abled to be verified via `yarn verify 0x**** --network truffle`.
