### ISSUE TITLE
I love it but I just can't get it verified 1.0.1 on etherscan.

### ISSUE THREAD

**Issue by GoodGoldDev** [hashlips-lab/nft-erc721-collection#22] opened 2022-02-23 09:40 UTC
It just gives me an error all the time. To make it worse, I also now deplyed it two times... ;( on the test network rinkeby).

yarn run v1.22.15
warning package.json: No license field
warning ../../../../../../../package.json: No license field
$ hardhat verify --constructor-args config/ContractArguments.ts 0xE621f8C8D9219D11c5a0Cb70bD6c4B04fAC6caEE --network rinkeby
Nothing to compile
No need to generate any newer typings.
Compiling 1 file with 0.8.9
Successfully submitted source code for contract
contracts/GoodGoldNFT.sol:GoodGoldNFT at 0xE621f8C8D9219D11c5a0Cb70bD6c4B04fAC6caEE
for verification on Etherscan. Waiting for verification result...

We tried verifying your contract GoodGoldNFT without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/GoodGoldNFT.sol:GoodGoldNFT at 0xE621f8C8D9219D11c5a0Cb70bD6c4B04fAC6caEE
for verification on Etherscan. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment] 2022-02-23 09:51
Hi @GoodGoldDev,
first of all, you should not call the `yarn deploy` command twice, that would deploy a new instance of the same contract on the chain. The verification step is completely independent and you can call it many times (if needed), but deploying just once.

There are many possible reasons for the verification steps to fail, please take a look at #17 and let me know if it helps.

**Comment by liarco** [comment] 2022-02-23 10:46
@GoodGoldDev unfortunately not, any transaction on the blockchain is final as soon as it's confirmed by the nodes. 😉

I'm gonna leave this issue open, waiting for some updates about the validation studd. Thank you.

**Comment by GoodGoldDev** [comment] 2022-02-23 11:32
I find it hard to see if I changed some of the variables you mentioned.
Maybe it is best to start all over again as a test? Deploy it and after that verify it asap. ;) 
For example, I did change the whitelist price and amount opened and closed it while not being verified.

**Comment by liarco** [comment] 2022-02-23 11:38
@GoodGoldDev that's understandable, if you changed the whitelist price then that might the problem (at least one of them), because that's exactly one of the constructor arguments used during deployment and they must match during verification.

Testing multiple times is fine, just make sure you rename your contract (e.g. if you want to call you final contract `MyNft` you may go for `MyNftTest1`, `MyNftTest2` and so on until you reach to the final testing... this is required in order to avoid #7).

I'm gonna close this now, but feel free to reply if you need anything about the same topic.

**Closed by liarco** 2022-02-23 11:38 UTC
Labels: feedback requested

**Comment by GoodGoldDev** [comment] 2022-02-23 15:28
It works flawless! Thanks a million it is a true piece of art you made!
