### ISSUE TITLE
yarn dev-server

### ISSUE THREAD

**Issue by droidft** [hashlips-lab/nft-erc721-collection#296] opened 2022-05-25 13:02 UTC
Hi guys, I keep getting a port in use error when i try yarn dev-server no matter how many times i restart the entire process on my Macbook M1, can anyone help? 
:
Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
at Server.setupListenHandle [as _listen2] (net.js:1331:16)
at listenInCluster (net.js:1379:12)
at GetAddrInfoReqWrap.doListen [as callback] (net.js:1516:7)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:8) {
code: 'EADDRINUSE',
errno: -48,
syscall: 'listen',
address: '127.0.0.1',
port: 8080
}
error Command failed with exit code 1.

**Comment by liarco** [comment] 2022-06-07 11:44
Duplicate of #299.

**Closed by liarco** 2022-06-07 11:44 UTC
