### ISSUE TITLE
Issue deploying contract to rinkeby network

### ISSUE THREAD

**Issue by crakctg** [hashlips-lab/nft-erc721-collection#26] opened 2022-02-23 21:07 UTC
Hi Liarco, thanks for the video. When I try to deploy my contract on the rinkeby test net this is what I get: HardhatError: HH110: Invalid JSON-RPC response received: invalid project id....... error Command failed with exit code 1. Do you know the solution for this?

**Comment by crakctg** [comment] 2022-02-23 21:12
Note I am working on windows with node version 16.14.0 and yarn 1.22.15

**Comment by crakctg** [comment] 2022-02-23 21:27
Note again I have tried with both version 1.0.0 and 1.0.1 of the contract. I got it to work once as a test but now for some reason it wont work...

**Comment by liarco** [comment] 2022-02-23 22:35
Hi @crakctg,
from your comment on YouTube:

> Also when changing my contract name it changes the contracts but in the collectionconfig.ts file it does not change my contract name

I'm afraid you choose an invalid name and unfortunately there is no validation on the input (I should definitely add that). The contract name should be in `PascalCase`, no `-`, no `.`, no digits at the beginning. For example, if you run `yarn rename-contract my-own-token` then you end up with a broken project folder and you have to start over.

So I think that your error (`HardhatError: HH110: Invalid JSON-RPC response received: invalid project id`) might be related to your broken codebase. Please let me know if this is the case.

**Comment by crakctg** [comment] 2022-02-23 22:45
When renaming my contract I just used "Aliens" or "MyNFT" and it still gave me this broken error. 

This is the full error I'm getting 

HardhatError: HH110: Invalid JSON-RPC response received: invalid project id

    at parseJsonResponse (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\hardhat\src\internal\util\jsonrpc.ts:47:11)
    at HttpProvider._fetchJsonRpcResponse (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:173:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpProvider.request (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:55:29)
    at async GanacheGasMultiplierProvider._isGanache (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:317:30)
    at async GanacheGasMultiplierProvider.request (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:306:23)
    at async EthersProviderWrapper.send (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
    at async getSigners (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:45:20)
    at async getContractFactoryByAbiAndBytecode (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:280:21)
    at async main (C:\Users\nickm\OneDrive\Desktop\Test 2 Data\nft-erc721-collection-1.0.0\smart-contract\scripts\1_deploy.ts:15:20)
error Command failed with exit code 1.

**Comment by liarco** [comment] 2022-02-23 22:52
Oh, my fault, I think I actually misunderstood your error...
`invalid project id` might be referring to your Infura project ID are you sure you copied the correct endpoint from the Infura dashboard? It should be in the format `https://rinkeby.infura.io/v3/YOUR_OWN_PROJECT_ID`.

I get your exact same error if I don't set this correctly in my `.env` file.

**Comment by crakctg** [comment] 2022-02-23 23:10
I see, I have everything formatted correctly but I will try creating another project on infura, getting the new endpoints and trying that. I will let you know if that fixes the issue. Thanks

**Comment by liarco** [comment] 2022-02-23 23:33
> I see, I have everything formatted correctly but I will try creating another project on infura, getting the new endpoints and trying that. I will let you know if that fixes the issue. Thanks

I'm gonna leave the issue open waiting for feedback. Please also make sure you are actually updating your configuration in `.env` and not in `.env.example`. You know, this can happen since the content will be exactly the same at the beginning.

**Comment by crakctg** [comment] 2022-02-23 23:40
Yes for sure, I have been updating the .env file each time, not the example file

**Comment by crakctg** [comment] 2022-02-24 00:31
I just did everything again, created a new infura project and used those endpoints and it still gives me the same error. Not quite sure what is happening

**Comment by liarco** [comment] 2022-02-24 01:03
> I just did everything again, created a new infura project and used those endpoints and it still gives me the same error. Not quite sure what is happening

I'm so sorry to hear this, unfortunately I'm not able to reproduce this unless I do one of the following:
- no `.env` file
- bad configuration in `.env`
- bad endpoint (network or type, it must be https)

I have to close this since it seems like I'm not able to help you any further (this may be unrelated to the project itself), but please feel free to reopen the issue if you have any additional information for troubleshooting this thing.

**Closed by liarco** 2022-02-24 01:03 UTC
Labels: feedback requested
