### ISSUE TITLE
TS2345: Argument of type 'Provider | Signer' is not assignable to parameter of type 'Signer | Provider | undefined'.

### ISSUE THREAD

**Issue by Yash094** [hashlips-lab/nft-erc721-collection#407] opened 2022-09-26 07:54 UTC
Getting the following error while running the minting dapp

TS2345: Argument of type 'Provider | Signer' is not assignable to parameter of type 'Signer | Provider | undefined'.

**Comment by liarco** [comment] 2022-09-26 11:31
Hi, when you open an issue you are provided with a template that you have to fill in to help us troubleshooting your issue. Any issue with missing information is considered invalid.

I tested the whole project a few minutes ago in order to release a new patch and I couldn't reproduce this error in any way. Please make sure you provide full instructions on how to reproduce the issue or I'll have to close this issue as invalid.

Thank you for your understanding.

**Comment by Yash094** [comment] 2022-09-26 19:03
### General information
| Description | Value |
| --- | --- |
| Project version | v2.4.4 |
| Operating system and version | Windows 10 64-bit 21H2 |
| NodeJS version | v16.14.0 |
| NPM version | 8.3.1 |
| Yarn version | 1.22.15 |
| Truffle version | Not used |

### Describe the bug
TS2345: Argument of type 'Provider | Signer' is not assignable to parameter of type 'Signer | Provider | undefined'. #407
This error popups when trying to run the minting dapp 


### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):
1. Clone repo
2. npm install in smart-contract and minting dapp directory
3. npm run compile in smart contract directory
4. npm run dev in minting dapp directory

**Comment by liarco** [comment] 2022-09-26 19:15
Hi, thank you for the additional information, now I think I have a better understanding of whats going on. First of all this project is using Yarn as package manager. I cannot be 100% sure this is the problem, but NPM is probably skipping our `yarn.lock` file so it's not guaranteed that you are using the same dependencies as required by my code.
This may break the whole app.

Also, you are running `dev` which is not the correct script, the correct one to run a local dev server is `dev-server` (so `yarn dev-server` or `npm run dev-server`, but again, NPM is probably not gonna work).

My suggestion is to follow my videos tutorials carefully and stick with the official dependencies unless you have strong experience with the differences between NPM and Yarn.

Here are all the the tutorials about this tool: https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials
Here you can find a video about how to setup your machine on Windows: https://youtu.be/zjlg-0622PU
Here you can find a quick video that shows how to run a full collection from start to finish: https://youtu.be/AFrsJRLrZEM

I hope this can help, I'm gonna close this issue since I have no reason to think there is anything wrong with my code. If you really wanna use this tool in a custom way (e.g. using NPM instead of Yarn), you may ask for support from the community in the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions).

Have a great day!

**Closed by liarco** 2022-09-26 19:15 UTC
