### ISSUE TITLE
Error why?

### ISSUE THREAD

**Issue by Catzskull** [hashlips-lab/nft-erc721-collection#300] opened 2022-05-26 21:10 UTC
<img width="586" alt="Screen Shot 2022-05-26 at 5 09 21 PM" src="https://user-images.githubusercontent.com/102982983/170580698-9063498f-f2b0-4302-83b8-4425e06d0336.png">

**Comment by 0xZoom-eth** [comment] 2022-05-27 09:21
the address you tried to mint from is not in the WL. Did you update it in the Whitelist.json and then run 'build' on the minting dapp to upload the new list and merkletree and then upload those new files to your hosting system?

**Comment by nftkk** [comment] 2022-05-30 23:48
same issue. on local server it works perfect. but not on public. i build and update the files on hosting too. but same error :(

**Comment by liarco** [comment] 2022-06-07 11:39
Hi @Catzskull,
I run all the steps multiple times just to make sure nothing was broken now for some strange reasons, but I couldn't reproduce the error in any way on my side. Also, you are not providing the requested information for a bug report so I must close this. If you are looking for community support you should take a look at the "Discussions" section.

Thank you for your understanding.

**Closed by liarco** 2022-06-07 11:39 UTC
