### ISSUE TITLE
How to use provenance-hash?

### ISSUE THREAD

**Issue by Lypheal** [hashlips-lab/nft-erc721-collection#136] opened 2022-03-16 12:29 UTC
Is there an implementation for provenance hash in the contract? If yes, Please tell me how to use it. If not, could you consider adding it?

**Comment by liarco** [comment] 2022-03-17 16:12
Hi @Lypheal, this is a duplicate of #1. I hope this helps.

**Closed by liarco** 2022-03-17 16:12 UTC
