### ISSUE TITLE
No indication whether mint has been successful or not

### ISSUE THREAD

**Issue by BobbyBorisov** [hashlips-lab/nft-erc721-collection#52] opened 2022-03-01 12:53 UTC
Hey guys!

I am following your tutorial on youtube but I think there should be an indication whether the mint was successful or not, even a loading spinner would be good addition. Is this a bug or this has not been implemented at all?

Thank you!
Cheers

**Comment by liarco** [comment] 2022-03-01 17:49
Duplicate of #11.

**Closed by liarco** 2022-03-01 17:49 UTC

**Comment by DevKoos** [comment] 2022-03-11 19:42
This would be awesome to see in the dapp. A simple Success textbox would do the work. Curious if someone has already implemented by their own.
