### ISSUE TITLE
Automatic network switching.

### ISSUE THREAD

**Issue by Shiba-Matic** [hashlips-lab/nft-erc721-collection#168] opened 2022-03-23 17:36 UTC
Automatic network switching.

I like the way we can connect the various wallets and allow auto-switching networks instead of prompts, which is a lot more personal.

Thank you for your selflessness.

**Comment by liarco** [comment] 2022-04-02 00:53
Hi @Shiba-Matic, thank you for your suggestion, but this is duplicate of #150.

**Closed by liarco** 2022-04-02 00:53 UTC
