### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Exper-t** [hashlips-lab/nft-erc721-collection#362] opened 2022-07-23 01:21 UTC
After restarting 2 times on version 2.4.2 I have again got this error after entering "yarn verify"+contract address+" --network truffle"

This is the error I get:
**"Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."**

However I don't see what is wrong with my API key as it is made from the Etherscan.io website just as Hashlips did in this video: https://www.youtube.com/watch?v=Zhmj4PiJ-GA

at the time 50:50

Could someone please help me solve this.

Many Thanks

**Comment by liarco** [comment] 2022-07-23 09:47
Hi @Exper-t, issues are for bug reports only (I have to close this as invalid since it misses all the required information that you deleted).
Community support for questions can be found [here](https://github.com/hashlips-lab/nft-erc721-collection/discussions).

Make sure you watch my [video series](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) about this project (especially ep.04 about configuration) because it goes more into details. I guess you may be using an Etherscan API while working on a different network like Polygon.

**Comment by Exper-t** [comment] 2022-07-23 15:41
I am using the Ethereum.io api because I am deploying the contract first to the rinkby testnet then to the ethereum blockchain. I still don't know why it is saying my API key is invalid. Could you please help. Many thanks

**Comment by mcbeav** [comment] 2022-07-23 17:46
I am having the same exact issue. Is there possibly a bug here? Instead of assuming it's user error, I have gone through the same steps. Using the same video series, I have followed the steps exactly, and I have tried this about 10 times now. I have tried new etherscan.io API keys, I tried replacing the ENV variables inside the hardhat config with the API key directly, but I get the same result of invalid API key everytime when attempting to verify, and it happens on all of the Ethereum test networks.

**Comment by liarco** [comment] 2022-07-23 17:57
Hi @Exper-t and @mcbeav,
I just checked the Etherscan status page and is seems like they are having issues with their API since a few days.

https://etherscan.freshstatus.io/

I guess we have to wait until that's solved before we can investigate any further.

**Comment by Exper-t** [comment] 2022-07-23 18:10
Thank You very much liarco!

**Comment by liarco** [comment] 2022-07-23 18:13
> Thank You very much liarco!

You are welcome! If the problem persists even a few hours after their status is back ok, then please open a proper issue with all the required info in order to help me troubleshooting.

Thank you!

**Comment by mcbeav** [comment] 2022-07-24 06:54
Thank you for the feedback, and checking into it! Appreciate the help!

**Comment by mikemanila** [comment] 2022-07-25 00:52
**Having the same issue as well and it has been 5 days now. Hope it gets sorted out soon!** 

Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment] 2022-07-25 00:55
I'm temporarily reopen the issue so people can find it easily. Unfortunately Etherscan is still having issues with their API, that's pretty sad :(

**Comment by locache** [comment] 2022-07-25 15:40
Having the same issue today.

**Comment by mikemanila** [comment] 2022-07-25 20:19
Hoping this gets solved soon!

**Comment by liarco** [comment] 2022-07-25 23:58
We are using the verification library from Hardhat, they got this error reported for the first time yesterday: https://github.com/NomicFoundation/hardhat/issues/2989

[Etherscan's status page](https://etherscan.freshstatus.io/) says the API should work again now. I didn't have the time to test this on my side yet.

Can anyone please try again?

Thank you.

**Comment by Exper-t** [comment] 2022-07-26 00:53
I have tried again and still am getting the error of invalid api key despite Etherscan's status website insisting that the API services are operational. Just really frustrating.

**Comment by locache** [comment] 2022-07-26 10:47
It just worked worked for me today! So its likely intermittent issues with Etherscan rinkeby test network

**Comment by svensei** [comment] 2022-07-26 16:48
Yep the problem is solved finally, it was etherscan api problem -.-

**Comment by liarco** [comment] 2022-07-27 20:44
Thanks everyone for the information. I'm gonna close this now since it looks like it has nothing to do with our code.

**Closed** 2022-07-27 20:44 UTC
Labels: invalid

**Comment by sardarahmedkhan505** [comment] 2024-01-16 14:56
I am facing the issue : 
_Error in plugin @nomicfoundation/hardhat-verify: Invalid API Key_
